### ISSUE TITLE
sin(19°) not korrekt

### ISSUE THREAD

**Issue by ich-bin-der-ich-bin** [galculator/galculator#60]
Hello,

incidentally I had to verify sin(19) (not in Radian but in Degree). I receive 0.294040325232, what is wrong.
I use calculator 2.1.4 with Arch Linux (mostly recent packages).

Regards

Michael

**Comment by Xevion** [comment]
I get the same answer - in Gradians mode.

- sin(19) in Gradians = `0.294040325232`
- sin(19) in Degrees = `0.325568154457`

I think this may be a user error on @ich-bin-der-ich-bin's part.

<sub>Pop!_OS 22.04 (Ubuntu) with Galculator 2.1.4</sub>

**Comment by ich-bin-der-ich-bin** [comment]
Hello,

I've got to apologize.
Xevion is absolutely right. The supposed error is due to changing to the wrong degree measure. I recovered that recently but until now I didn't have the time to correct this here.
