### ISSUE TITLE
Programmer mode?

### ISSUE THREAD

**Issue by Rafagd** [galculator/galculator#7]
Is there a reason to not have a programmer mode, specialized for bitwise operations like and, or, xor, shift, etc?

I really miss this feature, along with the 64bit grid that mate-calc had which let you toggle a individual bit of the number that was on screen.

**Comment by galculator** [comment]
Hi, you may already perform bitwise operations with binary, octal or hexadecimal numbers in scientific mode (View -> Scientific mode). We do not plan to introduce a bit grid, however.
